_BASE_: "mask_rcnn_R_50_FPN_3x_point_sup_coco.yaml"
DATASETS:
  TRAIN: ("coco_2017_train_points_n10_v1_without_masks",)
  TEST: ("dental_plague_dataset_val",)

SOLVER:
  STEPS: (9000, 9500)
  MAX_ITER: 10000
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  AMP:
    ENABLED: True

TEST:
  EVAL_PERIOD: 5000
#  EVAL_FLAG: 1

INPUT:
  SAMPLE_POINTS: 5
  MIN_SIZE_TRAIN: (512, ) # (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512  # 最小测试尺寸
  MAX_SIZE_TEST: 512  # 最大测试尺寸
