_BASE_: "../Base-RCNN-FPN.yaml"
DATASETS:
  TRAIN: ("dental_plague_dataset_train",)
  TEST: ("dental_plague_dataset_val",)

MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: 90

SOLVER:
  STEPS: (9000, 9500)
  MAX_ITER: 10000
  IMS_PER_BATCH: 16
  BASE_LR: 0.02

INPUT:
  MIN_SIZE_TRAIN: (512, ) # (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 512
  MIN_SIZE_TEST: 512  # 最小测试尺寸
  MAX_SIZE_TEST: 512  # 最大测试尺寸
